### ISSUE TITLE
Extend 'canDeploy" and add "record-deployment" for full pact-broker CLI typescript support

### ISSUE THREAD

**Issue by stefanhalbritterpdg** [pact-foundation/pact-js-cli#11]
### Feature description

As a developer, I would like to see next to `publishPacts`
* a full support of `canDeploy`. Currently I cannot pass the target environment, only tags. The corresponding `pact-broker` cli supports both as well as the docker image passing this parameters
* `recordDeployment`. Currently only `publisPacts` and `canDeploy` are (partially) supported next to the pact-broker cli
Thereby it would be aligned with the full pact-broker cli

### Use case

Hi folks,

personally I like it more to use the pact-cli programatically directly in our node projects as code. 

```
pact-publish.mjs

function publishPacts() {
  // doing some fetching token stuff with fetch
  const token = ....

  await pact.publishPacts({
    ...
    pactBrokerToken: token
  })
}
publishPacts()
```

```
pact-canDeploy.mjs

fucntion canDeploy() {
  // doing some fetching token stuff with fetch
  const token = ....
  ...
  
  await pact.canDeploy({
    ...
    environment: 'production'
    pactBrokerToken: token
    ...
  })
}
canDeploy()
```

```
pact-recordDeployment.mjs

fucntion recordDeployment() {
  // doing some fetching token stuff with fetch
  const token = ....

  await pact.recordDeployment({
    ...
    environment: 'production'
    pactBrokerToken: token
    ...
  })
}
recordDeployment()
 
```
```
package.json

   ...
  "scripts": {
      "pact:can-i-deploy": "node pact-can-i-deploy.mjs",
      "pact:publish": "node pact-publish.mjs",
      "pact:record-deployment": "node pact-record-deployment.mjs"
      ...
  }
```

* If you support `publishPacts` and (partially) `canDeploy` as typescript convenient functions next to the CLI calls, this should imho be added as well
* Doing it that way feels more close to our development "philosophy". I can execute the same "typescript chunks" locally and reuse them as tasks in our pipeline
* Especially echoing the pact broker token from a script and passing it to the docker pact-broker cli call was a pain in the neck imho. Imho it is easier to directly pass it as typescript code to a PACT typescript convenient function
* It feels more natural than installing the pact-cli package in a Github pipeline action or using the docker image

Maybe you already planned to implement this in the future but there was no capacity (yet).
If it sounds like a good idea, maybe we can talk about a contribution.

Kind regards

**Comment by YOU54F** [comment]
Hey Stefan,

we generally recommend installing the cli tools directly, as a user would get the latest corresponding changes without needing to wait for them to be implemented in client language wrappers.

We also lack visibility into who are using the cli tools directly or via wrappers, so often the additional flags are not added until people request them.

more broadly, i think i would like to replace the ruby implementation with rust 

my wip is here https://github.com/YOU54F/pact_cli

your proposals sound good, and I’d be more than happy to accept contributions to extend the current func to be in line with the cli tools, and for any enhancements that make it easier for programmatic use

**Comment by stefanhalbritterpdg** [comment]
Thank you for the quick response @YOU54F!

when it is recommended using the cli tools directly, then we probably script this call with typescript this way and we would renounce to extend the language wrapper for typescript

```
execSync(
            `pact-broker publish  pacts --branch ..... --broker-base-url .....`,
            { stdio: 'inherit' },
        )
```

Kind regards
Stefan
