### ISSUE TITLE
pactflow executable not found: ENOENT while spawning it 

### ISSUE THREAD

**Issue by bahamut657** [pact-foundation/pact-js-cli#12]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Alpine Linux 
- **Pact Node version**: 15.0.2
- **Node Version**: 20.12.0
- **Other Versions**: 

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

pactflow executable is runnable

### Actual behaviour

```
 npx --package=@pact-foundation/pact-cli -c 'pactflow'
Need to install the following packages:
@pact-foundation/pact-cli@15.0.2
Ok to proceed? (y) y
/Users/jacopo/.npm/_npx/262fdb08f55da9f8/node_modules/@pact-foundation/pact-cli/bin/pactflow.js:13
    throw error;
    ^

Error: spawnSync standalone/darwin-arm64-2.4.6/pact/bin/pactflow ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at Object.spawnSync (node:child_process:876:24)
    at Object.<anonymous> (/Users/jacopo/.npm/_npx/262fdb08f55da9f8/node_modules/@pact-foundation/pact-cli/bin/pactflow.js:8:40)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync standalone/darwin-arm64-2.4.6/pact/bin/pactflow',
  path: 'standalone/darwin-arm64-2.4.6/pact/bin/pactflow',
  spawnargs: []
}
```

Node.js v20.12.2

### Steps to reproduce

Try to use pactflow command provided by pact-cli package

**Comment by bahamut657** [comment]
Even installing the dependency statically in the package.json file the error persists.
It seems related to the cwd used while calling `standalone/darwin-arm64-2.4.6/pact/bin/pactflow`

**Comment by YOU54F** [comment]
There are alpine specific dependencies required as the ruby runtime which the pact cli tools rely on is built against glibc not musl, please see the following wiki

https://github.com/pact-foundation/pact-ruby-standalone/wiki/Using-the-pact-ruby-standalone-with-Alpine-Linux-Docker

**Comment by YOU54F** [comment]
hmm your repro mentions alpine linux, but your console commands are from macos 🤔

**Comment by YOU54F** [comment]
will get a fix out shortly, have identified the issue (we use the full path for the other binaries, and I hadn't used the correct full path variable for the pactflow binary)

Cheers for the report!
