### ISSUE TITLE
Release to NPM

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-js-cli#2]
Think the repo is all setup for releasing for npm, just needs some agreement on versioning.

Some related discussion here

https://github.com/pact-foundation/pact-js-cli/pull/1#issuecomment-1625658197

Currently on release this will bump to v14.0.0 (its based on pact-js-cores previous versioning)

We could tag the release with the pact-ruby-standalone package version.

Do we want to retain the changelog? how relevant is it now, considering very little in their is relevant to these binaries (some will be)

**Comment by sw-tracker** [comment]
Can you please add this to NPM please?

How can I install it? and if I use this, do I still need to have the ruby library installed?

**Comment by YOU54F** [comment]
hey bud.

there is an open rfc with regards to migration of this functionality from pact js core 

https://github.com/pact-foundation/pact-js-core/issues/488

you may wish to comment on that as it is relevant to the release of this to npm

you can install pact-js-core today and utilise the bin stubs as described in the readme.

a ruby runtime is bundled in pact-js-core and this project, as it is still required but you do not need ruby installed on your own machine. even if you do it wont be used

**Comment by YOU54F** [comment]
Now released

https://www.npmjs.com/package/@pact-foundation/pact-cli

https://github.com/pact-foundation/pact-js-cli/releases

will be removed from pact-js-core in v15.x
